# Generated by Django 2.0.3 on 2018-03-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='root',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductCategory'),
        ),
    ]
