# Generated by Django 2.0.3 on 2018-03-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180329_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_state', models.IntegerField(choices=[(0, 'Принят в обработку'), (1, 'Выполнен')])),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.OrderCard')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('digits', models.IntegerField()),
                ('currency', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ProductCategory')),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Price')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='accessorydependency',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='accessorydependency',
            name='accessory_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_for', to='shop.Product'),
        ),
    ]
